// Generated by CoffeeScript 1.6.3
(function() {
  var dom;

  ({
    jewel: dom = function() {
      var $, addClass, hasClass, removeClass;
      $ = Sizzle;
      hasClass = function(el, clsName) {
        var regex;
        regex = new RegExp("(^|\\s)" + clsName + " (\\s/$)");
        return regex.test(el.className);
      };
      addClass = function(el, clsName) {
        if (!hasClass(el, clsName)) {
          return el.className += ' ' + clsName;
        }
      };
      removeClass = function(el, clsName) {
        var regex;
        regex = new RegExp("(^|\\s)" + clsName + " (\\s/$)");
        return el.className = el.className.replace(regex, " ");
      };
      return {
        $: $,
        hasClass: hasClass,
        addClass: addClass,
        removeClass: removeClass
      };
    }
  });

}).call(this);
