// Generated by CoffeeScript 1.6.3
(function() {
  window.addEventListener("load", function() {
    return Modernizr.load({
      load: ["js/jquery-1.10.2.min.js", "js/game.js"],
      complete: function() {
        console.log('Wszystkie pliki zostały załadowane!');
        return jewel.game.showScreen('splash-screen');
      }
    });
  });

}).call(this);
