// Generated by CoffeeScript 1.6.3
(function() {
  window.addEventListener("load", function() {
    var _this = this;
    return Modernizr.load({
      load: ["js/sizzle.js", "js/dom.js", "js/game.js"],
      complete: function() {
        return console.log('Wszystkie pliki zostały załadowane!');
      }
    });
  });

}).call(this);
